[package]
name = "soarus-io"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
ply-rs = { workspace = true }
soarus-core = { path = "../soarus-core" }
las = { version = "0.9", features = ["laz"] }   # pure-Rust LAZ decoder
