[package]
name = "soarus-filters"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
hashbrown = { workspace = true }
rayon = { workspace = true }
soarus-core = { path = "../soarus-core" }
